### ISSUE TITLE
Is this project deprecated? Will there be migration from bintray?

### ISSUE THREAD

**Issue by petertrr** [bashor/DefinitelyKotlin#28]
I can see, that there hasn't been much activity in this project for a long time. However, the old artifacts seem to have been working fine even with newer versions of Kotlin. But, due to bintray shutdown, dependencies have become unreliable. Also, there is no ready-to-use Kotlin wrapper for jQuery, other that this project.
So my question is, are there any plans to continue this project, or any sort of official Kotlin/JS wrapper for jQuery? Or any official recommendations?

**Comment by bashor** [comment]
> But, due to bintray shutdown, dependencies have become unreliable.

All previously published versions are available through `jcenter`. JFrog had promised to keep jcenter ([source](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)): 
> We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

> So my question is, are there any plans to continue this project, or any sort of official Kotlin/JS wrapper for jQuery? Or any official recommendations?

We are not going to publish new versions for libraries, the current plan is to improve [Dukat](https://github.com/Kotlin/dukat/) and promote it instead. 

Dukat is already integrated with our Gradle plugin so you can simply get required declarations for your npm dependencies, to find out more, check out
https://kotlinlang.org/docs/js-external-declarations-with-dukat.html#generate-external-declarations-at-build-time

**Comment by bashor** [comment]
Also, all previously published versions are available on npmjs.com under `@kotlin-externals` scope.

**Comment by petertrr** [comment]
Thanks, I have somehow missed the part about duktat in docs. FYI, jcenter sometimes works unreliably now. While it has been announced that is will be available as a read-only repository, it sometimes gives 4xx errors when trying to download stuff.
Anyway, thank you very much for the clarification, I'll definitely check out dukat.
